/* ============================================================
   NEXUS BOOM GAMES — STORE / DATA LAYER
   ============================================================ */

const GAMES = [
  // ---- ORIGINAL 7 GAMES ----
  { id:'shooter',    title:'Galaxy Defender',   description:'Defend the galaxy from relentless alien invaders. Survive endless waves, collect power-ups, and dominate the leaderboard!', genre:'Shooter',   category:'shooter',   emoji:'🚀', rating:4.9, players:'18.4K', tags:['Action','Space','Waves'],    path:'games/shooter/index.html',    featured:true,  trending:true,  color1:'#0a0020', color2:'#1a0060', glowColor:'rgba(0,180,255,0.15)', accentColor:'#00b4ff', badge:'🔥 HOT' },
  { id:'racing',     title:'Neon Racer',         description:'Blaze through neon-lit highways at extreme speed. Dodge traffic, collect boost pickups, and race to the top!',              genre:'Racing',    category:'racing',    emoji:'🏎️', rating:4.7, players:'12.1K', tags:['Speed','Dodge','Neon'],     path:'games/racing/index.html',     featured:true,  trending:true,  color1:'#200010', color2:'#600020', glowColor:'rgba(255,50,50,0.15)',   accentColor:'#ff3232', badge:'⚡ FAST' },
  { id:'football',   title:'Street Football',    description:'Fast-paced 2-minute street football. Score goals, beat the AI, and become the street champion!',                           genre:'Sports',    category:'sports',    emoji:'⚽', rating:4.5, players:'9.3K',  tags:['Sports','VS AI','2D'],      path:'games/football/index.html',   featured:false, trending:true,  color1:'#001800', color2:'#003800', glowColor:'rgba(16,185,129,0.15)', accentColor:'#10b981', badge:'⭐ FUN' },
  { id:'platformer', title:'Pixel Jumper',        description:'A classic platformer with modern flair. Jump through treacherous levels, avoid enemies, collect coins and reach the exit!', genre:'Platformer',category:'platformer',emoji:'🕹️', rating:4.6, players:'7.8K',  tags:['Jump','Levels','Coins'],    path:'games/platformer/index.html', featured:true,  trending:false, color1:'#180020', color2:'#400060', glowColor:'rgba(168,85,247,0.15)', accentColor:'#a855f7', badge:'🎮 CLASSIC' },
  { id:'zombie',     title:'Dead Zone',           description:'Survive endless zombie hordes in this top-down survival shooter. Manage ammo, fight boss waves, and stay alive!',          genre:'Survival',  category:'survival',  emoji:'🧟', rating:4.8, players:'15.6K', tags:['Survival','Horror','Waves'], path:'games/zombie/index.html',     featured:false, trending:true,  color1:'#001008', color2:'#003018', glowColor:'rgba(239,68,68,0.15)',   accentColor:'#ef4444', badge:'💀 INTENSE' },
  { id:'puzzle',     title:'2048 Neon',           description:'The legendary 2048 puzzle — reimagined with a neon cyberpunk aesthetic. Merge tiles, chase the high score!',              genre:'Puzzle',    category:'puzzle',    emoji:'🧩', rating:4.4, players:'21.2K', tags:['Puzzle','Strategy','Relax'], path:'games/puzzle/index.html',     featured:false, trending:false, color1:'#001820', color2:'#003848', glowColor:'rgba(0,212,255,0.12)',   accentColor:'#00d4ff', badge:'🧠 THINK' },
  { id:'arcade',     title:'Cyber Breakout',      description:'Destroy neon bricks with your paddle in this futuristic Breakout. Power-ups, boss bricks, multi-ball chaos!',             genre:'Arcade',    category:'arcade',    emoji:'👾', rating:4.6, players:'11.5K', tags:['Arcade','Bricks','Classic'], path:'games/arcade/index.html',     featured:false, trending:true,  color1:'#181000', color2:'#382800', glowColor:'rgba(245,158,11,0.15)',  accentColor:'#f59e0b', badge:'🕹️ RETRO' },

  // ---- 20 NEW GAMES ----
  { id:'snake',      title:'Snake Neon',          description:'The legendary snake game reimagined with stunning neon trails. Grow longer, avoid yourself, and chase the high score!',    genre:'Arcade',    category:'arcade',    emoji:'🐍', rating:4.7, players:'24.5K', tags:['Classic','Snake','Neon'],   path:'games/snake/index.html',      featured:true,  trending:true,  color1:'#001a08', color2:'#003318', glowColor:'rgba(57,255,20,0.15)',   accentColor:'#39ff14', badge:'🐍 CLASSIC' },
  { id:'asteroids',  title:'Asteroid Crisis',     description:'Pilot your ship through an asteroid field. Split rocks, avoid debris, and survive the ever-growing cosmic threat!',        genre:'Shooter',   category:'shooter',   emoji:'☄️', rating:4.7, players:'8.9K',  tags:['Space','Retro','Physics'],  path:'games/asteroids/index.html',  featured:true,  trending:true,  color1:'#000a18', color2:'#001530', glowColor:'rgba(0,212,255,0.12)',   accentColor:'#00d4ff', badge:'☄️ EPIC' },
  { id:'tetris',     title:'Tetris Neon',          description:'The world-famous block puzzle game with electrifying neon visuals. Clear lines, level up, and beat your high score!',     genre:'Puzzle',    category:'puzzle',    emoji:'🔷', rating:4.9, players:'32.1K', tags:['Classic','Tetris','Blocks'], path:'games/tetris/index.html',     featured:true,  trending:true,  color1:'#0a001a', color2:'#200040', glowColor:'rgba(124,58,237,0.15)',  accentColor:'#7c3aed', badge:'🔷 VIRAL' },
  { id:'pacman',     title:'Pac-Man Neon',         description:'Eat all the dots, dodge the glowing ghosts, and use power pellets to turn the tables in this timeless neon maze!',        genre:'Arcade',    category:'arcade',    emoji:'👻', rating:4.8, players:'19.7K', tags:['Classic','Maze','Ghosts'],  path:'games/pacman/index.html',     featured:true,  trending:true,  color1:'#181000', color2:'#302000', glowColor:'rgba(255,215,0,0.15)',   accentColor:'#ffd700', badge:'👻 ICONIC' },
  { id:'tower',      title:'Cyber Tower Defense', description:'Build towers, upgrade defenses, and stop relentless enemy waves from breaching your fortress in this strategic masterpiece!',genre:'Strategy',  category:'strategy',  emoji:'🏰', rating:4.8, players:'7.2K',  tags:['Strategy','Tower','Waves'], path:'games/tower/index.html',      featured:true,  trending:false, color1:'#001020', color2:'#002040', glowColor:'rgba(0,212,255,0.15)',   accentColor:'#00d4ff', badge:'🏰 STRATEGY' },
  { id:'flappy',     title:'Flappy Neon',          description:'Tap to fly your neon drone through glowing pipe corridors. One tap, infinite challenge!',                                 genre:'Arcade',    category:'arcade',    emoji:'🚁', rating:4.3, players:'28.9K', tags:['Tap','Endless','Hard'],    path:'games/flappy/index.html',     featured:false, trending:true,  color1:'#000a14', color2:'#001828', glowColor:'rgba(0,255,247,0.15)',   accentColor:'#00fff7', badge:'🚁 HARD' },
  { id:'invaders',   title:'Space Invaders',       description:'Classic alien invasion — defend Earth from wave after wave of descending extraterrestrial enemies with shields and power!', genre:'Shooter',   category:'shooter',   emoji:'👾', rating:4.6, players:'13.4K', tags:['Classic','Aliens','Retro'], path:'games/invaders/index.html',   featured:false, trending:false, color1:'#000818', color2:'#001030', glowColor:'rgba(57,255,20,0.15)',   accentColor:'#39ff14', badge:'👾 RETRO' },
  { id:'pong',       title:'Pong Battle',          description:'The original game that started it all, now with neon visuals, power-ups and a ruthless AI opponent!',                     genre:'Sports',    category:'sports',    emoji:'🏓', rating:4.4, players:'16.2K', tags:['Classic','Ball','VS AI'],   path:'games/pong/index.html',       featured:false, trending:false, color1:'#080810', color2:'#141428', glowColor:'rgba(255,255,255,0.1)',  accentColor:'#ffffff', badge:'🏓 OG' },
  { id:'golf',       title:'Cyber Mini Golf',      description:'Physics-based mini golf on neon-lit courses. Aim, adjust power, and sink holes in the fewest shots possible!',            genre:'Sports',    category:'sports',    emoji:'⛳', rating:4.5, players:'5.8K',  tags:['Golf','Physics','Aim'],     path:'games/golf/index.html',       featured:false, trending:false, color1:'#001806', color2:'#003010', glowColor:'rgba(16,185,129,0.15)', accentColor:'#10b981', badge:'⛳ CHILL' },
  { id:'whack',      title:'Whack-a-Zombie',       description:'Zombies are popping up from the ground! Click them fast before they escape. Test your reflexes in this manic arcade game!', genre:'Arcade',   category:'arcade',    emoji:'🔨', rating:4.3, players:'10.1K', tags:['Reflex','Click','Fun'],    path:'games/whack/index.html',      featured:false, trending:false, color1:'#0f1a00', color2:'#1e3300', glowColor:'rgba(239,68,68,0.12)',   accentColor:'#ef4444', badge:'🔨 FAST' },
  { id:'memory',     title:'Memory Matrix',        description:'The matrix flashes a pattern — can you repeat it? Push your memory to the limit across increasingly complex grids!',      genre:'Puzzle',    category:'puzzle',    emoji:'🧠', rating:4.6, players:'6.4K',  tags:['Memory','Brain','Pattern'], path:'games/memory/index.html',     featured:false, trending:false, color1:'#0a001a', color2:'#14003a', glowColor:'rgba(168,85,247,0.15)', accentColor:'#a855f7', badge:'🧠 BRAIN' },
  { id:'hockey',     title:'Air Hockey Pro',       description:'Fast and furious puck physics! Strike the puck with your mallet, score 7 goals before the AI does!',                     genre:'Sports',    category:'sports',    emoji:'🏒', rating:4.7, players:'8.7K',  tags:['Puck','Physics','VS AI'],   path:'games/hockey/index.html',     featured:false, trending:true,  color1:'#000820', color2:'#001040', glowColor:'rgba(0,212,255,0.15)',   accentColor:'#00d4ff', badge:'🏒 INTENSE' },
  { id:'fruit',      title:'Fruit Slice',          description:'Fruits are flying — slash them with your blade! Avoid bombs, chain combos, and achieve the highest score!',               genre:'Action',    category:'arcade',    emoji:'🍎', rating:4.5, players:'14.3K', tags:['Slash','Reflex','Combo'],   path:'games/fruit/index.html',      featured:false, trending:true,  color1:'#1a0808', color2:'#340f0f', glowColor:'rgba(239,68,68,0.15)',   accentColor:'#ef4444', badge:'🍎 SLASHER' },
  { id:'runner',     title:'Neon Runner',          description:'Run endlessly through a cyberpunk city. Jump over obstacles, slide under barriers, collect power cells!',                  genre:'Platformer',category:'platformer',emoji:'🏃', rating:4.6, players:'17.8K', tags:['Endless','Run','Jump'],    path:'games/runner/index.html',     featured:false, trending:true,  color1:'#08001a', color2:'#180038', glowColor:'rgba(124,58,237,0.15)', accentColor:'#7c3aed', badge:'🏃 RUN' },
  { id:'bubble',     title:'Bubble Blast',         description:'Aim and fire colored bubbles to create matches of 3 or more. Clear the board before the bubbles reach the bottom!',       genre:'Puzzle',    category:'puzzle',    emoji:'🫧', rating:4.4, players:'9.2K',  tags:['Bubble','Match','Aim'],    path:'games/bubble/index.html',     featured:false, trending:false, color1:'#001020', color2:'#001e38', glowColor:'rgba(0,212,255,0.12)',   accentColor:'#00d4ff', badge:'🫧 POP' },
  { id:'pinball',    title:'Neon Pinball',          description:'Launch the neon ball, hit glowing bumpers, score massive points, and keep the ball in play with your flippers!',          genre:'Arcade',    category:'arcade',    emoji:'⚪', rating:4.7, players:'6.9K',  tags:['Physics','Bumpers','Score'],path:'games/pinball/index.html',    featured:false, trending:false, color1:'#0a0010', color2:'#1a0030', glowColor:'rgba(168,85,247,0.15)', accentColor:'#a855f7', badge:'⚪ PINBALL' },
  { id:'minesweeper',title:'Cyber Minesweeper',    description:'Reveal the safe cells, flag the mines! The classic logic puzzle reimagined with cyberpunk aesthetics.',                   genre:'Puzzle',    category:'puzzle',    emoji:'💣', rating:4.5, players:'7.1K',  tags:['Logic','Classic','Mines'], path:'games/minesweeper/index.html',featured:false, trending:false, color1:'#001010', color2:'#002020', glowColor:'rgba(0,212,255,0.1)',    accentColor:'#00d4ff', badge:'💣 TENSE' },
  { id:'frogger',    title:'Cyber Crossy',         description:'Hop across neon-lit roads and glowing rivers. Dodge speeding vehicles and jump on moving platforms to reach safety!',      genre:'Arcade',    category:'arcade',    emoji:'🐸', rating:4.4, players:'8.3K',  tags:['Hop','Dodge','Classic'],   path:'games/frogger/index.html',    featured:false, trending:false, color1:'#001808', color2:'#003010', glowColor:'rgba(57,255,20,0.12)',   accentColor:'#39ff14', badge:'🐸 CLASSIC' },
  { id:'tanks',      title:'Tank Battle',          description:'Command your neon tank through destructible arenas! Aim precisely, blast enemies, and dominate the battlefield!',          genre:'Shooter',   category:'shooter',   emoji:'🎯', rating:4.7, players:'11.2K', tags:['Tank','Battle','Action'],  path:'games/tanks/index.html',      featured:false, trending:true,  color1:'#0a1000', color2:'#182000', glowColor:'rgba(245,158,11,0.15)',  accentColor:'#f59e0b', badge:'🎯 BATTLE' },
  { id:'stacker',    title:'Neon Stacker',          description:'Stack the moving blocks as accurately as possible. The higher you go, the narrower the blocks! How high can you reach?',  genre:'Arcade',    category:'arcade',    emoji:'📦', rating:4.4, players:'5.6K',  tags:['Stack','Timing','Precision'],path:'games/stacker/index.html',   featured:false, trending:false, color1:'#080a18', color2:'#101428', glowColor:'rgba(0,212,255,0.12)',   accentColor:'#00d4ff', badge:'📦 STACKER' },
];

const CATEGORIES = [
  { id:'all',       label:'All Games',      icon:'🎮', count: GAMES.length },
  { id:'shooter',   label:'Shooter',        icon:'🚀' },
  { id:'racing',    label:'Racing',         icon:'🏎️' },
  { id:'sports',    label:'Sports',         icon:'⚽' },
  { id:'platformer',label:'Platformer',     icon:'🕹️' },
  { id:'survival',  label:'Survival',       icon:'🧟' },
  { id:'puzzle',    label:'Puzzle',         icon:'🧩' },
  { id:'arcade',    label:'Arcade',         icon:'👾' },
  { id:'strategy',  label:'Strategy',       icon:'🏰' },
];

const ACHIEVEMENTS = [
  { id:'first_login', name:'First Login',    desc:'Welcome to the arena!',            icon:'🏆' },
  { id:'first_fav',   name:'Game Collector', desc:'Added your first favorite game',   icon:'❤️' },
  { id:'play_3',      name:'Gamer',          desc:'Played 3 different games',         icon:'🎮' },
  { id:'play_all',    name:'Platform Master',desc:'Played all available games',       icon:'👑' },
  { id:'night_owl',   name:'Night Owl',      desc:'Playing after midnight',           icon:'🦉' },
  { id:'play_10',     name:'Dedicated',      desc:'Played 10 different games',        icon:'🔥' },
];

/* ---- LocalStorage Store ---- */
const Store = (() => {
  const PREFIX = 'nexus_';
  function get(key) { try { const v=localStorage.getItem(PREFIX+key); return v?JSON.parse(v):null; } catch { return null; } }
  function set(key, value) { try { localStorage.setItem(PREFIX+key, JSON.stringify(value)); } catch {} }
  function getFavorites() { return get('favorites') || []; }
  function setFavorites(ids) { set('favorites', ids); }
  function isFavorite(id) { return getFavorites().includes(id); }
  function toggleFavorite(id) {
    const favs=getFavorites(); const idx=favs.indexOf(id);
    if (idx===-1) favs.push(id); else favs.splice(idx,1);
    setFavorites(favs); return idx===-1;
  }
  function getRecentlyPlayed() { return get('recent') || []; }
  function addRecentlyPlayed(id) { const r=getRecentlyPlayed().filter(x=>x!==id); r.unshift(id); set('recent',r.slice(0,10)); }
  function getUnlockedAchievements() { return get('achievements') || []; }
  function unlockAchievement(id) { const u=getUnlockedAchievements(); if(!u.includes(id)){u.push(id);set('achievements',u);return true;} return false; }
  function getStats() { return { played:getRecentlyPlayed().length, favorites:getFavorites().length, achievements:getUnlockedAchievements().length }; }
  return { get, set, getFavorites, isFavorite, toggleFavorite, getRecentlyPlayed, addRecentlyPlayed, getUnlockedAchievements, unlockAchievement, getStats };
})();
